export const PRODUCTS = [
  {
    id: "1",
    slug: "kumkumadi-face-serum",
    name: "Kumkumadi Radiance Serum",
    sanskritName: "कुमकुमादि तैलम्",
    category: "skin",
    concerns: ["dullness", "pigmentation", "aging"],
    doshas: ["pitta", "vata"],
    price: 1299,
    mrp: 1599,
    shortDesc: "Traditionally used for glowing, radiant skin with 16 precious herbs",
    description:
      "Formulated following the classical Ashtanga Hridayam text, this serum blends Kumkuma (saffron), Chandana (sandalwood), and Manjistha in a base of pure sesame oil. Traditionally used in Ayurveda for brightening skin tone and supporting an even complexion.",
    ingredients: ["Kumkuma (Saffron)", "Chandana (Sandalwood)", "Manjistha", "Lodhra", "Padmaka", "Sesame Oil Base"],
    benefits: [
      "Traditionally supports a luminous, even skin tone",
      "May help reduce the appearance of dark spots",
      "Nourishes Vata-type dry, dull skin",
      "Rich in antioxidants from classical Ayurvedic herbs",
    ],
    howToUse:
      "After cleansing, take 3–4 drops on fingertips. Gently press onto face in upward circular motions. Use nightly for best results. For Pitta skin, apply on a thin layer of rose water first.",
    doctorNote:
      "Arvaya recommends this serum especially for patients with Pitta-dominant skin who experience pigmentation after sun exposure. The Chandana calms reactive skin while Kumkuma traditionally supports brightening. Arvaya",
    images: ["/products/kumkumadi-1.jpg"],
    stock: 45,
    featured: true,
    rating: 4.8,
    reviewCount: 127,
  },
  {
    id: "2",
    slug: "bhringraj-hair-oil",
    name: "Bhringraj Scalp Revival Oil",
    sanskritName: "भृङ्गराज तैलम्",
    category: "hair",
    concerns: ["hair-fall", "thinning", "scalp-issues"],
    doshas: ["vata", "pitta"],
    price: 849,
    mrp: 999,
    shortDesc: "The 'King of Hair' herb in a nourishing Brahmi-Amla base",
    description:
      "Bhringraj, revered in Ayurveda as Keshraj (ruler of hair), is combined with Brahmi, Amla, and Hibiscus in cold-pressed coconut oil. This classical formulation has been traditionally used to support hair roots and scalp health.",
    ingredients: ["Bhringraj", "Brahmi", "Amla (Indian Gooseberry)", "Hibiscus", "Methi (Fenugreek)", "Cold-pressed Coconut Oil"],
    benefits: [
      "Traditionally used to support hair strength and reduce excessive shedding",
      "Nourishes the scalp to address dryness and flakiness",
      "May support natural hair colour over time with regular use",
      "Cooling effect balances Pitta-related scalp inflammation",
    ],
    howToUse:
      "Warm slightly. Part hair and apply directly to scalp in sections. Massage in circular motions for 5 minutes. Leave for minimum 1 hour or overnight. Wash with mild shampoo. Use 2–3 times per week.",
    doctorNote:
      "Bhringraj has been studied for its potential to support hair follicle health. Arvaya recommends overnight oiling for Vata types prone to dryness and scalp tension. Arvaya",
    images: ["/products/bhringraj-1.jpg"],
    stock: 62,
    featured: true,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "3",
    slug: "neem-tulsi-face-wash",
    name: "Neem & Tulsi Clarifying Cleanser",
    sanskritName: "निम्ब-तुलसी मुखप्रक्षालन",
    category: "skin",
    concerns: ["acne", "oiliness", "sensitivity"],
    doshas: ["kapha", "pitta"],
    price: 549,
    mrp: 649,
    shortDesc: "Gentle daily cleanser for oily, acne-prone skin with cooling Neem",
    description:
      "A gel-based cleanser using Neem's purifying properties alongside Tulsi's balancing effect. Formulated for Kapha-dominant skin types who experience congestion, enlarged pores, or frequent breakouts. Free from sulfates, parabens, and synthetic fragrance.",
    ingredients: ["Neem Leaf Extract", "Tulsi (Holy Basil)", "Aloe Vera", "Tea Tree", "Mulethi (Licorice)", "Rose Hydrosol"],
    benefits: [
      "Gently purifies without stripping natural moisture",
      "Traditionally used to address skin congestion and breakouts",
      "Mulethi supports an even skin tone over time",
      "Suitable for daily use, even on sensitive combination skin",
    ],
    howToUse:
      "Dampen face. Take a coin-sized amount, lather on hands, and apply in gentle circular motions. Rinse thoroughly with cool water. Use morning and night.",
    doctorNote:
      "For patients with Kapha-Pitta skin presenting with frequent breakouts, Arvaya often starts with this cleanser before adding actives. Neem is cooling and clarifying without being aggressive. Arvaya",
    images: ["/products/neem-tulsi-1.jpg"],
    stock: 78,
    featured: true,
    rating: 4.6,
    reviewCount: 203,
  },
  {
    id: "4",
    slug: "ashwagandha-night-cream",
    name: "Ashwagandha Deep Restore Night Cream",
    sanskritName: "अश्वगन्धा निशा क्रीम",
    category: "skin",
    concerns: ["aging", "dryness", "dullness"],
    doshas: ["vata", "kapha"],
    price: 1099,
    mrp: 1299,
    shortDesc: "Adaptogenic night cream for stressed, fatigued skin",
    description:
      "Ashwagandha (Withania somnifera), one of Ayurveda's most revered Rasayana herbs, is combined with Shea butter, Shatavari, and Licorice in this overnight recovery cream. Traditionally used to support skin's resilience and natural renewal.",
    ingredients: ["Ashwagandha Root Extract", "Shatavari", "Mulethi (Licorice)", "Shea Butter", "Jojoba Oil", "Vetiver"],
    benefits: [
      "Supports overnight skin recovery and hydration",
      "Ashwagandha is an adaptogen traditionally used for vitality",
      "May help reduce the appearance of fatigue-related dullness",
      "Rich texture deeply nourishes Vata-type dry, mature skin",
    ],
    howToUse:
      "After evening cleansing and serum, take a small amount and warm between fingers. Press gently into face, neck, and décolletage. Do not rub, press to encourage absorption.",
    doctorNote:
      "Arvaya formulated this for patients experiencing 'skin fatigue', the dullness and dehydration that comes from stress, poor sleep, and seasonal changes. Ashwagandha's adaptogenic properties make it uniquely suited for the night routine. Arvaya",
    images: ["/products/ashwagandha-cream-1.jpg"],
    stock: 34,
    featured: true,
    rating: 4.9,
    reviewCount: 56,
  },
  {
    id: "5",
    slug: "triphala-hair-mask",
    name: "Triphala Strength & Shine Hair Mask",
    sanskritName: "त्रिफला केश लेप",
    category: "hair",
    concerns: ["dryness", "damage", "dandruff"],
    doshas: ["vata", "pitta", "kapha"],
    price: 749,
    mrp: 899,
    shortDesc: "The tri-fruit Ayurvedic classic for every hair type",
    description:
      "Triphala (Amalaki, Bibhitaki, Haritaki) has been used for thousands of years in Ayurveda for its balancing properties. This hair mask combines Triphala powder with Shikakai, egg-free protein, and cold-pressed oils for a weekly deep treatment.",
    ingredients: ["Amalaki (Amla)", "Bibhitaki", "Haritaki", "Shikakai", "Reetha (Soapnut)", "Argan Oil", "Fenugreek"],
    benefits: [
      "Balancing for all three doshas, suitable for all hair types",
      "Traditionally used to strengthen hair from root to tip",
      "Shikakai gently cleanses and adds natural shine",
      "Supports scalp microbiome balance",
    ],
    howToUse:
      "Mix 2 tablespoons with warm water or yogurt to form a paste. Apply to scalp and lengths. Cover with a warm towel. Leave for 30–45 minutes. Rinse thoroughly. Use weekly.",
    doctorNote:
      "Triphala's tridoshic nature makes this mask suitable for almost everyone. It's Arvaya's first recommendation for patients unsure of their hair type. Arvaya",
    images: ["/products/triphala-mask-1.jpg"],
    stock: 91,
    featured: false,
    rating: 4.5,
    reviewCount: 74,
  },
  {
    id: "6",
    slug: "rose-sandalwood-toner",
    name: "Rose & Sandalwood Balancing Mist",
    sanskritName: "गुलाब चन्दन मुखवारि",
    category: "skin",
    concerns: ["sensitivity", "pigmentation", "dryness"],
    doshas: ["pitta", "vata"],
    price: 649,
    mrp: 749,
    shortDesc: "Cooling hydrating mist with pure rose water and white sandalwood",
    description:
      "Distilled rose water sourced from Kannauj, India's rose capital, blended with white sandalwood hydrosol and Vetiver. This mist sets the skin's natural moisture barrier and has a classically Pitta-soothing, cooling effect.",
    ingredients: ["Rose Hydrosol (Kannauj)", "White Sandalwood Hydrosol", "Vetiver Water", "Aloe Vera", "Glycerin"],
    benefits: [
      "Instantly cools and soothes reactive, sensitive skin",
      "Sets moisture before applying serums and oils",
      "Traditionally used to calm Pitta-type redness and irritation",
      "Can be used over makeup for a dewy refresh",
    ],
    howToUse:
      "After cleansing, hold 20cm from face and mist 2–3 times. Gently press into skin before it dries. Can also be used throughout the day for a cooling refresh. Store in refrigerator in summer.",
    doctorNote:
      "Rose water is one of Ayurveda's most time-tested skincare ingredients. For patients in hot climates or those with Pitta skin, Arvaya recommends misting before each step of their routine. Arvaya",
    images: ["/products/rose-toner-1.jpg"],
    stock: 55,
    featured: false,
    rating: 4.7,
    reviewCount: 118,
  },
  {
    id: "7",
    slug: "amla-brahmi-hair-tonic",
    name: "Amla-Brahmi Hair Tonic",
    sanskritName: "आमलकी-ब्राह्मी केश टॉनिक",
    category: "hair",
    concerns: ["greying", "thinning", "hair-fall"],
    doshas: ["vata", "pitta"],
    price: 899,
    mrp: 1049,
    shortDesc: "A daily scalp tonic of Amla and Brahmi, traditionally used to slow premature greying",
    description:
      "Amalaki (Indian gooseberry) and Brahmi are combined with Bhringraj and Jatamansi in a light, non-greasy base. In Ayurveda this Rasayana blend is traditionally used to nourish the roots, support natural pigment, and calm a stressed scalp.",
    ingredients: ["Amalaki (Amla)", "Brahmi", "Bhringraj", "Jatamansi", "Neelini (Indigo)", "Coconut-derived Base"],
    benefits: [
      "Traditionally used to slow premature greying",
      "Supports fullness and helps reduce thinning over time",
      "Jatamansi calms a stress-prone, Vata-type scalp",
      "Lightweight, absorbs without an oily residue",
    ],
    howToUse:
      "Part the hair and massage 8–10 drops into the scalp. Use daily or on alternate evenings. Leave on, no rinse required. Consistent use over 8–12 weeks gives the best results.",
    doctorNote:
      "Premature greying is often linked to Pitta and stress. Arvaya pairs Amla's vitamin C with Bhringraj and Brahmi to support the follicle from the root.",
    images: ["/products/amla-brahmi-1.jpg"],
    stock: 40,
    featured: true,
    rating: 4.6,
    reviewCount: 64,
  },
  {
    id: "8",
    slug: "japapushpa-hair-cleanser",
    name: "Japapushpa Gentle Hair Cleanser",
    sanskritName: "जपापुष्प केश प्रक्षालन",
    category: "hair",
    concerns: ["dandruff", "scalp-issues"],
    doshas: ["kapha", "pitta"],
    price: 599,
    mrp: 699,
    shortDesc: "A mild Hibiscus and Reetha cleanser for a flake-free, balanced scalp",
    description:
      "Japa (Hibiscus) is blended with Reetha (soapnut), Shikakai and Neem for a sulphate-free wash. Traditionally used to clear flakes and excess oil while keeping the scalp's natural balance intact.",
    ingredients: ["Japa (Hibiscus)", "Reetha (Soapnut)", "Shikakai", "Neem", "Amla", "Aloe Vera"],
    benefits: [
      "Gently clears dandruff and flakes without stripping",
      "Balances an oily, Kapha-prone scalp",
      "Hibiscus supports softness and shine",
      "Free from sulphates, silicones and parabens",
    ],
    howToUse:
      "Massage a coin-sized amount into a wet scalp, lather, and rinse thoroughly. Use 2–3 times a week. Follow with a hair oil or mask if needed.",
    doctorNote:
      "For recurrent flaking Arvaya starts with a gentle, non-stripping cleanser before any active treatment. Neem clears without aggravating a sensitive scalp.",
    images: ["/products/japapushpa-1.jpg"],
    stock: 70,
    featured: false,
    rating: 4.5,
    reviewCount: 52,
  },
  {
    id: "9",
    slug: "nalpamaradi-face-oil",
    name: "Nalpamaradi Brightening Face Oil",
    sanskritName: "नाल्पामरादि तैलम्",
    category: "skin",
    concerns: ["pigmentation", "dullness"],
    doshas: ["pitta", "kapha"],
    price: 1149,
    mrp: 1349,
    shortDesc: "The classical Nalpamaradi oil, traditionally used to even tone and lift dullness",
    description:
      "A faithful preparation of Nalpamaradi Thailam, built on the four Ficus barks with turmeric, Vetiver and Manjistha in a sesame base. Traditionally used to brighten uneven tone, soften tan, and support a clear, even complexion.",
    ingredients: ["Nalpamara (four Ficus barks)", "Turmeric (Nisha)", "Manjistha", "Vetiver (Usheera)", "Sesame Oil Base"],
    benefits: [
      "Traditionally used to fade pigmentation and tan",
      "Manjistha supports an even, luminous tone",
      "Nourishes without clogging when used sparingly",
      "Suited to Pitta and Kapha complexions",
    ],
    howToUse:
      "At night, warm 3–4 drops between the palms and press onto cleansed skin. For oily skin, use on alternate nights. Always follow daytime use with sunscreen.",
    doctorNote:
      "Nalpamaradi is one of Ayurveda's most trusted brightening oils. Arvaya recommends it for tan and post-sun pigmentation; patch test first for reactive skin.",
    images: ["/products/nalpamaradi-1.jpg"],
    stock: 38,
    featured: true,
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: "10",
    slug: "chandanadi-ubtan",
    name: "Chandanadi Clarifying Ubtan",
    sanskritName: "चन्दनादि लेप",
    category: "skin",
    concerns: ["acne", "oiliness", "dullness"],
    doshas: ["kapha", "pitta"],
    price: 699,
    mrp: 799,
    shortDesc: "A classic Sandalwood ubtan mask to clarify oily, congestion-prone skin",
    description:
      "A traditional lepa of Chandana (sandalwood), Multani mitti, Masoor and Lodhra. Mixed fresh into a paste, it is traditionally used to draw out excess oil, calm breakouts, and leave skin bright and matte.",
    ingredients: ["Chandana (Sandalwood)", "Multani Mitti (Fuller's Earth)", "Masoor (Red Lentil)", "Lodhra", "Rose Petal", "Turmeric"],
    benefits: [
      "Traditionally used to clarify oily, congested skin",
      "Sandalwood cools and calms active breakouts",
      "Gently exfoliates for an instant glow",
      "A weekly ritual for Kapha and Pitta skin",
    ],
    howToUse:
      "Mix 1–2 teaspoons with rose water or raw milk into a paste. Apply an even layer, leave 10–15 minutes until touch-dry, then rinse with cool water. Use 1–2 times a week.",
    doctorNote:
      "An ubtan is Ayurveda's original clarifying mask. Arvaya keeps this one gentle so it clears oil and dullness without over-drying the skin.",
    images: ["/products/chandanadi-1.jpg"],
    stock: 60,
    featured: false,
    rating: 4.6,
    reviewCount: 88,
  },
];

// About-page content (seeded into the DB; renders the timeline / credentials / pillars).
export const TIMELINE = [
  { year: "2016", event: "A BAMS practice opens, focused on skin and hair concerns at the root cause." },
  { year: "2018", event: "Patients start going home with in-clinic preparations; word spreads." },
  { year: "2021", event: "Arvaya launches, bringing those classical formulations to everyone." },
  { year: "2024", event: "The Prakriti quiz and personalised kits reach thousands across India." },
];

export const CREDENTIALS = [
  { iconName: "Award", title: "BAMS Qualified", description: "Formulated from a qualified Ayurvedic clinical practice, not a marketing desk." },
  { iconName: "BookOpen", title: "Rooted in Classical Texts", description: "Recipes reference the Charaka Samhita and Ashtanga Hridayam." },
  { iconName: "Users", title: "12+ Years in Clinic", description: "Refined on thousands of real skin and hair cases before reaching a shelf." },
  { iconName: "Leaf", title: "Small-batch & Natural", description: "Cold-pressed oils and steam-distilled extracts, free from parabens and sulfates." },
];

export const PILLARS = [
  { number: "01", title: "Personal, not generic", description: "Every routine begins with your Prakriti, never a one-size-fits-all shelf product." },
  { number: "02", title: "Classical, validated", description: "Ancient formulations, chosen with modern evidence and clinical experience." },
  { number: "03", title: "Clean & honest", description: "Simple, natural blends with claims grounded in tradition, never overstated." },
];

export const BLOG_POSTS = [
  {
    id: "1",
    slug: "vata-pitta-kapha-skin-types",
    title: "What Your Dosha Means for Your Skin, A Doctor's Guide",
    excerpt:
      "In Ayurveda, your skin type isn't just oily or dry, it's an expression of your unique Prakriti (प्रकृति), or constitution. Arvaya breaks down what Vata, Pitta, and Kapha skin look like, and how to care for each.",
    category: "Skin Ayurveda",
    author: "Arvaya",
    readTime: 7,
    publishedAt: "2024-03-15",
    image: "/blog/dosha-skin-guide.jpg",
  },
  {
    id: "2",
    slug: "ritucharya-seasonal-skincare",
    title: "Ritucharya: Adjusting Your Skincare for Each Season",
    excerpt:
      "Ritucharya (ऋतुचर्या), the Ayurvedic science of seasonal living, tells us that what works in winter won't work in summer. Here's how to adapt your skin and hair routine across India's six seasons.",
    category: "Ritucharya",
    author: "Arvaya",
    readTime: 9,
    publishedAt: "2024-02-28",
    image: "/blog/ritucharya-seasons.jpg",
  },
  {
    id: "3",
    slug: "bhringraj-hair-fall-science",
    title: "Bhringraj for Hair Fall: What the Research Actually Says",
    excerpt:
      "We look at the classical Ayurvedic evidence alongside modern research on Bhringraj (Eclipta prostrata). What does the science say about this revered herb, and how should you use it for best results?",
    category: "Hair Ayurveda",
    author: "Arvaya",
    readTime: 6,
    publishedAt: "2024-02-10",
    image: "/blog/bhringraj-research.jpg",
  },
];

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Ananya Krishnamurthy",
    location: "Bengaluru",
    rating: 5,
    title: "Finally, skincare that understands my skin",
    body: "I've struggled with oily, acne-prone skin for years. The quiz recommended the Neem Tulsi cleanser and Ashwagandha night cream, my combination skin needed exactly that balance. After 6 weeks, my pores look visibly smaller and I have fewer breakouts. The explanation about my Kapha-Pitta constitution finally made my skin make sense to me.",
    product: "Neem & Tulsi Clarifying Cleanser",
    verified: true,
  },
  {
    id: "2",
    name: "Rahul Mehta",
    location: "Mumbai",
    rating: 5,
    title: "The Bhringraj oil stopped my hair fall in 2 months",
    body: "I was sceptical, hair fall runs in my family. But the quiz showed I was Vata-dominant with scalp dryness as a root cause, not genetics alone. The Bhringraj oil twice a week, and I genuinely count fewer hairs in the drain now. Arvaya's reasoning in the results page made me trust the process.",
    product: "Bhringraj Scalp Revival Oil",
    verified: true,
  },
  {
    id: "3",
    name: "Deepa Venkataraman",
    location: "Chennai",
    rating: 5,
    title: "The quiz is genuinely accurate",
    body: "I've done many skin quizzes before, this one felt different. The questions about my lifestyle, diet, and the Chennai climate actually changed my results. The Kumkumadi serum it recommended worked beautifully on my pigmentation. And knowing Arvaya formulated it, not a marketing team, gave me confidence.",
    product: "Kumkumadi Radiance Serum",
    verified: true,
  },
];

export const QUIZ_QUESTIONS = [
  // Section A, About You
  {
    id: "age",
    section: "A",
    sectionTitle: "About You",
    question: "What is your age range?",
    type: "single",
    options: [
      { value: "under-18", label: "Under 18" },
      { value: "18-25", label: "18 – 25" },
      { value: "26-35", label: "26 – 35" },
      { value: "36-45", label: "36 – 45" },
      { value: "46-plus", label: "46 and above" },
    ],
  },
  {
    id: "gender",
    section: "A",
    sectionTitle: "About You",
    question: "How do you identify?",
    type: "single",
    options: [
      { value: "female", label: "Female" },
      { value: "male", label: "Male" },
      { value: "non-binary", label: "Non-binary / Gender-fluid" },
      { value: "prefer-not", label: "Prefer not to say" },
    ],
  },
  {
    id: "city-type",
    section: "A",
    sectionTitle: "About You",
    question: "What best describes your local climate?",
    type: "single",
    options: [
      { value: "hot-humid", label: "Hot & humid (coastal cities, South India)" },
      { value: "hot-dry", label: "Hot & dry (Rajasthan, parts of Maharashtra)" },
      { value: "cold-dry", label: "Cold & dry (North India winters, hills)" },
      { value: "temperate", label: "Temperate / Mild (Bengaluru, Pune)" },
      { value: "polluted-urban", label: "Heavy urban pollution (Delhi, Mumbai)" },
    ],
  },
  // Section B, Prakriti
  {
    id: "body-frame",
    section: "B",
    sectionTitle: "Your Prakriti (Constitution)",
    question: "Which best describes your natural body frame?",
    hint: "Prakriti (प्रकृति) is your unique constitution, the natural balance of energies you were born with.",
    type: "single",
    options: [
      { value: "lean-variable", label: "Lean, find it hard to gain weight, variable appetite", dosha: "vata", points: 3 },
      { value: "medium-athletic", label: "Medium, athletic build, strong appetite", dosha: "pitta", points: 3 },
      { value: "broad-sturdy", label: "Broad, sturdy, gain weight easily", dosha: "kapha", points: 3 },
    ],
  },
  {
    id: "skin-tendency",
    section: "B",
    sectionTitle: "Your Prakriti (Constitution)",
    question: "What is your skin's natural tendency?",
    type: "single",
    options: [
      { value: "dry-rough", label: "Dry, rough, gets flaky in cold or AC", dosha: "vata", points: 2 },
      { value: "sensitive-warm", label: "Sensitive, warm to touch, prone to redness or breakouts", dosha: "pitta", points: 2 },
      { value: "oily-thick", label: "Oily, thick, cool to touch, large pores", dosha: "kapha", points: 2 },
    ],
  },
  {
    id: "energy-pattern",
    section: "B",
    sectionTitle: "Your Prakriti (Constitution)",
    question: "How would you describe your natural energy and mind pattern?",
    type: "single",
    options: [
      { value: "restless-creative", label: "Restless, creative, mind moves fast, easily distracted", dosha: "vata", points: 2 },
      { value: "focused-intense", label: "Focused, goal-driven, can be perfectionist or irritable", dosha: "pitta", points: 2 },
      { value: "steady-calm", label: "Steady, calm, takes time to start but endures well", dosha: "kapha", points: 2 },
    ],
  },
  // Section C, Skin
  {
    id: "skin-concern",
    section: "C",
    sectionTitle: "Your Skin",
    question: "What is your primary skin concern right now?",
    type: "single",
    options: [
      { value: "acne", label: "Acne, breakouts, congestion" },
      { value: "dullness", label: "Dullness, lack of glow" },
      { value: "pigmentation", label: "Pigmentation, dark spots, uneven tone" },
      { value: "aging", label: "Fine lines, sagging, loss of firmness" },
      { value: "dryness", label: "Dryness, flakiness, tightness" },
      { value: "sensitivity", label: "Redness, sensitivity, reactive skin" },
    ],
  },
  {
    id: "skin-type",
    section: "C",
    sectionTitle: "Your Skin",
    question: "How does your skin feel by mid-afternoon (without products)?",
    type: "single",
    options: [
      { value: "oily", label: "Shiny all over, oily skin" },
      { value: "dry", label: "Tight and dull, dry skin" },
      { value: "combination", label: "Oily T-zone, dry cheeks, combination" },
      { value: "normal", label: "Comfortable, no major issues, normal" },
    ],
  },
  {
    id: "routine-complexity",
    section: "C",
    sectionTitle: "Your Skin",
    question: "What does your current skincare routine look like?",
    type: "single",
    options: [
      { value: "none", label: "Nothing, just water or soap" },
      { value: "basic", label: "Basic, cleanser and maybe a moisturiser" },
      { value: "moderate", label: "Moderate, cleanser, toner, serum, moisturiser" },
      { value: "elaborate", label: "Elaborate, multiple actives, SPF, eye cream, etc." },
    ],
  },
  {
    id: "skin-exposure",
    section: "C",
    sectionTitle: "Your Skin",
    question: "Which environmental factors does your skin face daily? (Select all that apply)",
    type: "multi",
    options: [
      { value: "sun", label: "Heavy sun exposure" },
      { value: "pollution", label: "Air pollution" },
      { value: "ac", label: "Air conditioning / heating" },
      { value: "screen", label: "Long hours in front of screens" },
      { value: "water", label: "Hard water" },
    ],
  },
  // Section D, Hair
  {
    id: "hair-concern",
    section: "D",
    sectionTitle: "Your Hair",
    question: "What is your primary hair concern?",
    type: "single",
    options: [
      { value: "hair-fall", label: "Excessive hair fall" },
      { value: "dandruff", label: "Dandruff or flaky scalp" },
      { value: "thinning", label: "Thinning, reduced volume" },
      { value: "greying", label: "Premature greying" },
      { value: "dryness", label: "Dryness, frizz, breakage" },
      { value: "scalp-issues", label: "Itchy, oily, or sensitive scalp" },
    ],
  },
  {
    id: "hair-type",
    section: "D",
    sectionTitle: "Your Hair",
    question: "What is your natural hair texture?",
    type: "single",
    options: [
      { value: "straight", label: "Straight, falls flat, gets oily quickly" },
      { value: "wavy", label: "Wavy, naturally some wave or body" },
      { value: "curly", label: "Curly, defined curls, prone to frizz" },
      { value: "coily", label: "Coily / kinky, tight coils, very dry" },
    ],
  },
  {
    id: "wash-frequency",
    section: "D",
    sectionTitle: "Your Hair",
    question: "How often do you wash your hair?",
    type: "single",
    options: [
      { value: "daily", label: "Daily" },
      { value: "alternate", label: "Every alternate day" },
      { value: "twice-week", label: "2–3 times a week" },
      { value: "weekly", label: "Once a week or less" },
    ],
  },
  {
    id: "chemical-treatments",
    section: "D",
    sectionTitle: "Your Hair",
    question: "Do you use any chemical treatments on your hair?",
    type: "single",
    options: [
      { value: "none", label: "No chemical treatments" },
      { value: "coloring", label: "Hair colouring / highlights" },
      { value: "straightening", label: "Straightening / rebonding / keratin" },
      { value: "multiple", label: "Multiple treatments" },
    ],
  },
  // Section E, Lifestyle
  {
    id: "diet",
    section: "E",
    sectionTitle: "Your Lifestyle",
    question: "What best describes your diet? (This helps us understand internal imbalances)",
    type: "single",
    options: [
      { value: "vegetarian", label: "Vegetarian" },
      { value: "non-veg", label: "Non-vegetarian" },
      { value: "vegan", label: "Vegan" },
      { value: "jain", label: "Jain (no root vegetables)" },
    ],
  },
  {
    id: "sleep",
    section: "E",
    sectionTitle: "Your Lifestyle",
    question: "How would you rate your sleep quality?",
    type: "single",
    options: [
      { value: "good", label: "Good, I sleep 7–8 hours, wake refreshed" },
      { value: "average", label: "Average, some disturbances, feel okay" },
      { value: "poor", label: "Poor, difficulty falling/staying asleep, wake tired" },
    ],
  },
];
